name: Deploy to EC2

on:
  workflow_run:
    workflows:
        - Java CI with Maven
    types:
      - completed

jobs:
  deploy:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            set -e 
            IMAGE = ${{secrets.DOCKER_USERNAME}}/streaming-demo-app:${{ github.sha }}
            echo "Deploying image : $IMAGE"
            docker pull $IMAGE
            docker stop streaming-demo || true
            docker rm streaming-demo || true
            docker run -d \
              --name streaming-demo \
              --restart unless-stopped \
              --env-file /home/ubuntu/app/.env \
              -p 8082:8082 \
              $IMAGE
            docker image prune -f
